Sprint 2/step 2
krokodila888/react-burger1 pull request #2
Opened 2023-02-28 23:57 UTC by krokodila888

2023-03-01 05:31 UTC, andryxxa93 requested changes
Здравствуйте! Проделана огромная работа 👍 
Что понравилось:
- Отлично организовано хранилище
- Для каждого запроса в api создан усилитель с необходимыми экшенами
- `Dnd` работает отлично

Что необходимо исправить:

- [ ] После оформления заказа необходимо очищать конструктор, чтобы пользователю не пришлось это делать самому.
- [ ] Чтобы пользователь понимал как добавить ингредиенты - для пустого конструктора добавьте подсказку. Например "Перетащите ингредиенты сюда".
- [ ] У вас совмещены две технологии - и хуки (`useSelector` и `useDispatch`) и `connect`. Нужно оставить что-то одно - рекомендую хуки оставить, это более современный подход.
- [ ] Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.
- [ ] Файл App.test.tsx необходимо удалить - он к проекту не относится.
- [ ] У подложки модалки должен быть полупрозрачный фон - пожалуйста посмотрите как фигме реализовано.
- [ ] Если конструктор пуст, то стоит скрывать или дизейблить кнопку "Оформить заказ".


**Можно лучше**
- Если при запросе произошла ошибка, то сообщение ошибки можно так же записывать в стейт и показывать пользователю, чтобы он понимал, что проихсодит. Например в модальном окне.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-01 05:31 UTC, andryxxa93 commented on src/components/IngredientCard/IngredientCard.jsx
> +export default connect(mapDispatchToProps, mapStateToProps) (IngredientCard);
**Необходимо исправить**
У вас совмещены две технологии - и хуки и connect. Нужно оставить что-то одно.

2023-03-01 05:31 UTC, andryxxa93 commented on src/components/IngredientDetails/IngredientDetails.jsx
> +  useSelector((state) => state.currentIngredientReducer.currentItem);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-01 23:57 UTC, krokodila888 commented
Все внесла. По содержимому хранилища для модальных окон - очищала при закрытии дял ингридиента, добавила там очищение и для заказа.

2023-03-02 06:56 UTC, andryxxa93 requested changes
- У вас после оформления заказа и закрытия модального окна срабатывает экшен - `CLEAR_CURRENT_INGREDIENT` и `REMOVE_ORDER`. Первый тут просто не нужен, а второй ничего не делает. Если посмотреть в `redux devtools`, то можно увидеть, что номер заказа остается в хранилище. Обратите внимание, что именно вы возвращаете в этом экшене. Так же необходимо возвращать к изначальному состоянию список ингредиентов, если в их запросе произошла ошибка. 
<img width="1440" alt="Снимок экрана 2023-03-02 в 09 52 59" src="https://user-images.githubusercontent.com/60173362/222353781-b849b9d7-ec83-4304-826f-66a2d38e5a17.png">
<img width="1439" alt="Снимок экрана 2023-03-02 в 09 52 51" src="https://user-images.githubusercontent.com/60173362/222353784-0a35c669-2ccc-47c9-a4db-1521361fc263.png">

2023-03-02 18:56 UTC, andryxxa93 reviewed
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-17 16:48 UTC, merged